name: API builder
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  CI: true

jobs:
  gradle-build:
    name: Gradle build and run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3.1.0
      - name: Setup Java
        uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.3

      - name: Run assemble
        run: gradle assemble --stacktrace

      - name: Run test
        run: gradle test --stacktrace

      - name: Archive test report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Test report
          path: api/build/reports/

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build_artifacts
          path: api/build/libs

  docker-build:
    name: Docker build and push image
    runs-on: ubuntu-latest
    needs:
      - gradle-build
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3.1.0
      - uses: actions/download-artifact@v3.0.1
        with:
          name: build_artifacts
          path: api/build/libs

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ghcr.io/rassafel/quicker-api
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          labels: |
            org.opencontainers.image.description=Quicker API Image
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: api
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
