name: Client builder
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

env:
  CI: true

jobs:
  node-build:
    name: Node build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3.1.0
      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          cache: 'yarn'
          cache-dependency-path: client/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run assemble
        run: yarn build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: build_artifacts
          path: client/.next

  docker-build:
    name: Docker build and push image
    runs-on: ubuntu-latest
    needs:
      - node-build
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3.1.0
      - uses: actions/download-artifact@v3.0.1
        with:
          name: build_artifacts
          path: client/.next

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            ghcr.io/rassafel/quicker-client
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
          labels: |
            org.opencontainers.image.description=Quicker Client Image
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to ghcr
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v3.2.0
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: client
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
